test

diff --git a/.github/workflows/loristest.yml b/.github/workflows/loristest.yml
--- a/.github/workflows/loristest.yml
+++ b/.github/workflows/loristest.yml
@@ -205,6 +205,37 @@ jobs:
            curl -v http://localhost:8000
 
 
+    - name: Wait for MySQL to be ready
+      run: |
+          #!/usr/bin/env bash
+          
+          set -euo pipefail
+          
+          max_attempts=10
+          attempt=0
+          
+          echo "Waiting for mysqld..."
+          
+          while ! mysqladmin ping -h db -u SQLTestUser --password="TestPassword" --silent; do
+            sleep 1
+            attempt=$((attempt + 1))
+            echo "$attempt attempts"
+            
+            if [ "$attempt" -ge "$max_attempts" ]; then
+              echo "MySQL did not respond after $max_attempts attempts. Creating a flag for GitHub Actions..."
+              echo "MySQL not started" > /tmp/mysql_error_flag
+              break
+            fi
+          done
+
+          if [ -f /tmp/mysql_error_flag ]; then
+            echo "MySQL is not responding. Please check the logs."
+            exit 1
+          else
+            echo "MySQL is up and running."
+          fi
+
+
     - name: Run Test Suite
       run: |
           vendor/bin/phpunit --configuration test/phpunit.xml --testsuite LorisAPITests --group api-${{ matrix.apiversion }}
